### ISSUE TITLE
node run dev MODULE_NOT_FOUND error on Tutorial 3

### ISSUE THREAD

**Issue by XiaosongWen** [techwithtim/Music-Controller-Web-App-Tutorial#15]
Hi I build the environment following the video, but got MODULE_NOT_FOUND error, the only different is I used node 12 in babel.config.json. Any help will be highly appreciated.

node run dev
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'C:\Users\wxsst\Desktop\Project\music\party_music\frontend\run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by punitzen** [comment]
@XiaosongWen - did you find any solution for this error, I'm kinda having the same error
The system cannot find the path specified.
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'F:\GitHub\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by XiaosongWen** [comment]
I didn't. I had the problem with my laptop, but when I switched to PC with the same process but somehow it magically worked. 
So i am sorry I cannot give any help.

**Comment by punitzen** [comment]
No problem @XiaosongWen, In root folder of my project, I had added '&' in name of folder which was causing issues. I removed it and it worked just fine.
